services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

#CodeCompliance
    CodeCompliance\Application\:
        resource: '../../src/CodeCompliance/Application/*'
        exclude: [ '../../src/CodeCompliance/Application/Service/*Service.php' ]

    CodeCompliance\Infrastructure\:
        resource: '../../src/CodeCompliance/Infrastructure/*'

    CodeCompliance\Domain\:
        resource: '../../src/CodeCompliance/Domain/*'

    is_not_unique_constant.task:
        class: CodeCompliance\Application\Checks\NotUnique\ConstantCheck

    is_not_unique_db_column.task:
        class: CodeCompliance\Application\Checks\NotUnique\DatabaseColumnCheck

    is_not_unique_db_table.task:
        class: CodeCompliance\Application\Checks\NotUnique\DatabaseTableCheck

    is_not_unique_method.task:
        class: CodeCompliance\Application\Checks\NotUnique\MethodCheck

    is_not_unique_transfer.task:
        class: CodeCompliance\Application\Checks\NotUnique\TransferNameCheck

    is_not_unique_transfer_property.task:
        class: CodeCompliance\Application\Checks\NotUnique\TransferPropertyCheck

    is_not_unique_module_name.task:
        class: CodeCompliance\Application\Checks\NotUnique\ModuleNameCheck

#PrivateApiUsed
    is_private_api_dp_is_used.task:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\DependencyProviderCheck

    is_private_api_extended.task:
        class: CodeCompliance\Application\Checks\PrivateApi\Extended\ExtendedCheck

    is_private_used_in_facade.task:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\FacadeCheck

    is_private_api_is_used_as_dp_in_business_model.task:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\DependencyInBusinessModelCheck

    is_private_api_is_initialized_in_business_model.task:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\InitializedInBusinessModelCheck

    is_private_api_is_used_in_persistence.check:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\PersistenceCheck

    is_private_api_from_persistence_is_used_in_b_m.check:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\PersistenceInBusinessModelCheck

    is_private_api_core_is_used_in_persistence.check:
        class: CodeCompliance\Application\Checks\PrivateApi\Used\CorePersistenceCheck

#IsPrivateApiIsOverwritten
    is_private_api_method_overwritten.check:
        class: CodeCompliance\Application\Checks\PrivateApi\MethodOverwritten\MethodIsOverwrittenCheck

    CodeCompliance\Application\Service\CodeComplianceService:
        class: CodeCompliance\Application\Service\CodeComplianceService
        arguments:
            - '@codebase.service'
            - {
                param1: '@is_not_unique_constant.task',
                param2: '@is_not_unique_db_column.task',
                param3: '@is_not_unique_db_table.task',
                param4: '@is_not_unique_method.task',
                param5: '@is_not_unique_transfer.task',
                param6: '@is_not_unique_transfer_property.task',
                param7: '@is_private_api_dp_is_used.task',
                param8: '@is_private_api_extended.task',
                param9: '@is_private_used_in_facade.task',
                param10: '@is_private_api_is_used_as_dp_in_business_model.task',
                param11: '@is_private_api_is_initialized_in_business_model.task',
                param12: '@is_private_api_is_used_in_persistence.check',
                param13: '@is_private_api_from_persistence_is_used_in_b_m.check',
                param14: '@is_private_api_core_is_used_in_persistence.check',
                param15: '@is_private_api_method_overwritten.check',
                param16: '@is_not_unique_module_name.task'
              }

    CodeCompliance\Application\Service\CodeComplianceServiceInterface: '@CodeCompliance\Application\Service\CodeComplianceService'

    business_factory.filter:
        class: CodeCompliance\Domain\Checks\Filters\BusinessFactoryFilter

    business_model.filter:
        class: CodeCompliance\Domain\Checks\Filters\BusinessModelFilter

    core_extension.filter:
        class: CodeCompliance\Domain\Checks\Filters\CoreExtensionFilter

    facade.filter:
        class: CodeCompliance\Domain\Checks\Filters\FacadeFilter

    ignore_list.filter:
        class: CodeCompliance\Domain\Checks\Filters\IgnoreListFilter

    ignore_list_parent.filter:
        class: CodeCompliance\Domain\Checks\Filters\IgnoreListParentFilter

    persistence.filter:
        class: CodeCompliance\Domain\Checks\Filters\PersistenceFilter

    private_api.filter:
        class: CodeCompliance\Domain\Checks\Filters\PrivateApiFilter

    plugin.filter:
        class: CodeCompliance\Domain\Checks\Filters\PluginFilter

    CodeCompliance\Domain\Service\FilterService:
        class: CodeCompliance\Domain\Service\FilterService
        arguments:
            - {
                param1: '@business_factory.filter',
                param2: '@business_model.filter',
                param3: '@core_extension.filter',
                param4: '@facade.filter',
                param5: '@ignore_list.filter',
                param6: '@persistence.filter',
                param7: '@private_api.filter',
                param8: '@plugin.filter',
                param9: '@ignore_list_parent.filter'
            }
