imports:
    - { resource: './Codebase/services.yaml' }
    - { resource: './CodeCompliance/services.yaml' }
    - { resource: './Core/Domain/services.yaml' }
    - { resource: './Core/Infrastructure/services.yaml' }
    - { resource: './ReleaseApp/services.yaml' }
    - { resource: './Upgrade/services.yaml' }
    - { resource: './Upgrader/services.yaml' }
    - { resource: './DynamicEvaluator/services.yaml' }
