name: Dependency updated

env:
  AUTH_TOKEN: ${{ secrets.PAT }}
  EVENT: upgrader_dependency_updated
  ORG: spryker-sdk
  REPO: sdk

on:
  push:
    branches:
      - master

jobs:
  trigger-external-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger external repository pr creation
        run: |
          curl -d "{\"event_type\": \"${EVENT}\"}" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${AUTH_TOKEN}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
